services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:9.4.19
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.34.3
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.31.2
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.16.2
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.1
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.21
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:3712018349a0ca866593b313afdec3236d99c67bc749da0f3dd89c186a1cb2b1
  radarr:
    image: lscr.io/linuxserver/radarr:5.25.0@sha256:36e43720c130ec2d3ed80726d2134af3c6644729f4750abc830fdda7fa71d1e1
