services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:9.5.21
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.34.3
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.32.1
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.16.2
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.4
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.22
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:2d8d07715382a58f83fdcd1751e08c736711d76eecf71135106312fd370af933
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:e26fbfd3782520c0bb820666f041ca056acfe187a8b95214ee1f47512cc05a29
