services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:9.5.21
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.35.2
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.32.4
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.16.4
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.6
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.22
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:d35b7cc5c198d24460f941173e56c243e46b9a627d31ce6a9b41734452a5b333
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:f08dda38e7d12e5a722d9a5cb6e54acaf63c8598fefeefec88effe0c0d0038dd
