services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:9.4.19
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.34.3
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.31.2
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.16.2
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.1
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.21
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:a3607697519be952c405fef14ab91d953089de81cd400460c3624ba9dd285bd9
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:e26fbfd3782520c0bb820666f041ca056acfe187a8b95214ee1f47512cc05a29
