services:
  unifi:
    image: ghcr.io/linuxserver/unifi-network-application:9.5.21
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden:1.35.2
  deconz:
    image: ghcr.io/deconz-community/deconz-docker:2.32.4
  frigate: 
    image: ghcr.io/blakeblackshear/frigate:0.16.4
  jellyfin:  
    image: ghcr.io/jellyfin/jellyfin:10.11.6
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.22
  transmission:
    image: ghcr.io/linuxserver/transmission:latest@sha256:29e631e2216f2d4a5e0f7274b3ef2045901efe1d13df78ef4d4d48e8a9f1b216
  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:ba2693dd704b84eb0b404d40b3902bd3e62a1768dc5ee0d89b1f1d7cd51a66eb
